name: cd

on:
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types:
      - completed
      
jobs:
  cd:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: Deploy and start server 🚀 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }} 
            export NVM_DIR="$HOME/.nvm" 
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
            npm i pm2 -g
            pm2 delete Timey 2> error.log
            git pull --ff-only 
            npm i 
            pm2 --name Timey start npm -- start

